import * as XLSX from 'xlsx';import Papa from 'papaparse';import type{RawRow,Ticket}from'../types';
export const normalize=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const aliases:Record<string,string[]>={id:['DIT no interne'],created:['DIT Date/Heure'],status:['DIT Etat'],nature:['DIT Nature'],requestType:['Type DIT'],opLast:['DIT Opérateur nom'],opFirst:['DIT Opérateur prénom'],techLast:['IT Intervenant nom'],techFirst:['IT Intervenant prénom'],duration:['IT Durée'],handling:['Tps Prise en charge'],response:['Tps Réponse'],resolution:['Tps Résolution'],agency:['Profil client AGENCES'],uo:['DIT Domaine lib'],customer:['DIT Raison sociale'],activity:['IT Activité article']};
const detect=(h:string[])=>Object.fromEntries(Object.entries(aliases).map(([k,n])=>[k,h.find(x=>n.some(a=>normalize(x)===normalize(a)))]))as Record<string,string|undefined>;
const text=(v:unknown)=>v==null?'':String(v).trim();const num=(v:unknown)=>{if(v==null||v==='')return null;const n=typeof v==='number'?v:Number(String(v).replace(',','.'));return Number.isFinite(n)&&n>=0?n:null};
const date=(v:unknown)=>{if(v instanceof Date&&!isNaN(v.getTime()))return v;if(typeof v==='number'){const p=XLSX.SSF.parse_date_code(v);return p?new Date(p.y,p.m-1,p.d,p.H,p.M,p.S):null}if(typeof v==='string'){const f=v.match(/^(\d{2})\/(\d{2})\/(\d{4})(?:\s+(\d{2}):(\d{2}))?/);if(f)return new Date(+f[3],+f[2]-1,+f[1],+(f[4]||0),+(f[5]||0));const d=new Date(v);return isNaN(d.getTime())?null:d}return null};
const person=(f:unknown,l:unknown)=>[text(f),text(l).toUpperCase()].filter(Boolean).join(' ');
export async function readFile(file:File):Promise<RawRow[]>{if(file.name.toLowerCase().endsWith('.csv'))return await new Promise((resolve,reject)=>Papa.parse<RawRow>(file,{header:true,skipEmptyLines:true,complete:r=>resolve(r.data),error:reject}));const b=await file.arrayBuffer();const w=XLSX.read(b,{type:'array',cellDates:true});return XLSX.utils.sheet_to_json<RawRow>(w.Sheets[w.SheetNames[0]],{defval:null,raw:true})}
export function consolidate(rows:RawRow[]){const m=detect(rows[0]?Object.keys(rows[0]):[]);if(!m.id)throw new Error('La colonne « DIT no interne » est introuvable.');const groups=new Map<string,RawRow[]>();let rejected=0;for(const r of rows){const id=text(r[m.id]).toUpperCase();if(!id){rejected++;continue}const g=groups.get(id);g?g.push(r):groups.set(id,[r])}const tickets:Ticket[]=[];for(const[id,g]of groups){const first=(k:string)=>{const c=m[k];return c?g.map(r=>r[c]).find(v=>v!=null&&v!==''):null};const nums=(k:string)=>{const c=m[k];return c?g.map(r=>num(r[c])).filter((v):v is number=>v!=null):[]};const people=(fk:string,lk:string)=>{const fc=m[fk],lc=m[lk];return[...new Set(g.map(r=>person(fc?r[fc]:null,lc?r[lc]:null)).filter(Boolean))]};const issues:string[]=[];const one=(k:string)=>{const v=nums(k);if(new Set(v.map(x=>x.toFixed(6))).size>1)issues.push(`Valeurs multiples : ${k}`);return v[0]??null};const dates=m.created?g.map(r=>date(r[m.created!])).filter((v):v is Date=>!!v):[];const states=m.status?[...new Set(g.map(r=>text(r[m.status!])).filter(Boolean))]:[];if(states.length>1)issues.push('Plusieurs états pour le même DIT');tickets.push({id,createdAt:dates.length?new Date(Math.min(...dates.map(d=>d.getTime()))):null,status:states.length?states[states.length-1]:'',nature:text(first('nature')),requestType:text(first('requestType')),agency:text(first('agency')),uo:text(first('uo')),customer:text(first('customer')),activity:text(first('activity')),operators:people('opFirst','opLast'),technicians:people('techFirst','techLast'),handling:one('handling'),response:one('response'),resolution:one('resolution'),duration:nums('duration').reduce((a,b)=>a+b,0),sourceRows:g.length,issues})}return{tickets,rejected}}
export const average=(a:(number|null)[])=>{const v=a.filter((x):x is number=>x!=null);return v.length?v.reduce((s,x)=>s+x,0)/v.length:null};export const median=(a:(number|null)[])=>{const v=a.filter((x):x is number=>x!=null).sort((a,b)=>a-b);if(!v.length)return null;const i=Math.floor(v.length/2);return v.length%2?v[i]:(v[i-1]+v[i])/2};export const formatDuration=(h:number|null)=>{if(h==null)return'N/D';const m=Math.round(h*60);if(m<60)return`${m} min`;const d=Math.floor(m/1440),hr=Math.floor((m%1440)/60),mn=m%60;return d?`${d} j ${hr} h ${mn} min`:`${hr} h ${mn} min`};
