import*as XLSX from'xlsx';import Papa from'papaparse';import type{RawRow,Ticket,Intervention,BaseRecord}from'../types';
const norm=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const aliases:Record<string,string[]>={dit:['DIT no interne'],it:['IT N°','IT No','IT Numero'],created:['DIT Date/Heure'],status:['DIT Etat'],uo:['DIT Domaine lib'],agency:['Profil client AGENCES'],customer:['DIT Raison sociale'],activity:['IT Activité article'],opLast:['DIT Opérateur nom'],opFirst:['DIT Opérateur prénom'],techLast:['IT Intervenant nom'],techFirst:['IT Intervenant prénom'],duration:['IT Durée'],handling:['Tps Prise en charge'],response:['Tps Réponse'],resolution:['Tps Résolution']};
const detect=(h:string[])=>Object.fromEntries(Object.entries(aliases).map(([k,a])=>[k,h.find(x=>a.some(y=>norm(x)===norm(y)))]))as Record<string,string|undefined>;
const txt=(v:unknown)=>v==null?'':String(v).trim(),number=(v:unknown)=>{if(v==null||v==='')return null;const n=typeof v==='number'?v:Number(String(v).replace(',','.'));return Number.isFinite(n)&&n>=0?n:null};
const asDate=(v:unknown)=>{if(v instanceof Date&&!isNaN(v.getTime()))return v;if(typeof v==='number'){const x=XLSX.SSF.parse_date_code(v);return x?new Date(x.y,x.m-1,x.d,x.H,x.M,x.S):null}if(typeof v==='string'){const d=new Date(v);if(!isNaN(d.getTime()))return d;const f=v.match(/^(\d{2})\/(\d{2})\/(\d{4})(?:\s+(\d{2}):(\d{2}))?/);return f?new Date(+f[3],+f[2]-1,+f[1],+(f[4]||0),+(f[5]||0)):null}return null};
export async function readFile(file:File):Promise<RawRow[]>{if(file.name.toLowerCase().endsWith('.csv'))return await new Promise((ok,ko)=>Papa.parse<RawRow>(file,{header:true,skipEmptyLines:true,complete:r=>ok(r.data),error:ko}));const b=await file.arrayBuffer(),w=XLSX.read(b,{type:'array',cellDates:true});return XLSX.utils.sheet_to_json<RawRow>(w.Sheets[w.SheetNames[0]],{defval:null,raw:true})}
export function buildModels(rows:RawRow[]){const m=detect(rows[0]?Object.keys(rows[0]):[]);if(!m.dit)throw new Error('Colonne « DIT no interne » introuvable.');if(!m.it)throw new Error('Colonne « IT N° » introuvable.');const group=(key:string)=>{const c=m[key]!,map=new Map<string,RawRow[]>();let rejected=0;for(const r of rows){const id=txt(r[c]).toUpperCase();if(!id){rejected++;continue}const a=map.get(id);a?a.push(r):map.set(id,[r])}return{map,rejected}};const dits=group('dit'),its=group('it');
const base=(g:RawRow[]):BaseRecord=>{const first=(k:string)=>{const c=m[k];return c?g.map(r=>r[c]).find(v=>v!=null&&v!==''):null},nums=(k:string)=>{const c=m[k];return c?g.map(r=>number(r[c])).filter((v):v is number=>v!=null):[]},people=(f:string,l:string)=>{const fc=m[f],lc=m[l];return[...new Set(g.map(r=>[txt(fc?r[fc]:null),txt(lc?r[lc]:null).toUpperCase()].filter(Boolean).join(' ')).filter(Boolean))]},one=(k:string,issues:string[])=>{const v=nums(k);if(new Set(v.map(x=>x.toFixed(6))).size>1)issues.push(`Valeurs multiples : ${k}`);return v[0]??null};const issues:string[]=[],dates=m.created?g.map(r=>asDate(r[m.created!])).filter((d):d is Date=>!!d):[],states=m.status?[...new Set(g.map(r=>txt(r[m.status!])).filter(Boolean))]:[];if(states.length>1)issues.push('Plusieurs états');return{createdAt:dates.length?new Date(Math.min(...dates.map(d=>d.getTime()))):null,status:states.at(-1)||'',uo:txt(first('uo')),agency:txt(first('agency')),customer:txt(first('customer')),activity:txt(first('activity')),operators:people('opFirst','opLast'),technicians:people('techFirst','techLast'),handling:one('handling',issues),response:one('response',issues),resolution:one('resolution',issues),duration:one('duration',issues)??0,sourceRows:g.length,issues}};
const tickets:Ticket[]=[...dits.map].map(([ticketId,g])=>({ticketId,...base(g)}));const interventions:Intervention[]=[...its.map].map(([interventionId,g])=>({interventionId,ticketId:txt(g[0][m.dit!]).toUpperCase(),...base(g)}));return{tickets,interventions,rejectedDit:dits.rejected,rejectedIt:its.rejected}}
export const avg=(a:(number|null)[])=>{const v=a.filter((x):x is number=>x!=null);return v.length?v.reduce((s,x)=>s+x,0)/v.length:null};export const med=(a:(number|null)[])=>{const v=a.filter((x):x is number=>x!=null).sort((a,b)=>a-b);if(!v.length)return null;const i=Math.floor(v.length/2);return v.length%2?v[i]:(v[i-1]+v[i])/2};export const duration=(h:number|null)=>{if(h==null)return'N/D';const m=Math.round(h*60),d=Math.floor(m/1440),hr=Math.floor(m%1440/60),mn=m%60;return d?`${d} j ${hr} h ${mn} min`:hr?`${hr} h ${mn} min`:`${mn} min`};
